version: "3.3"

services:

  nginx:
    image: nginx:latest
    networks:
      - frontend    
    ports:
      - 8080:80
    depends_on:
      - php
    volumes:
      - ./dokuwiki-2017-02-19e:/usr/share/nginx/html
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro


  php:
    # image: php:7.2-rc-fpm-alpine
    build:
      context: .
      dockerfile: dokuwiki-php.Dockerfile
    networks:
      - frontend
      - middleend
    volumes:
      - ./dokuwiki-2017-02-19e:/usr/share/nginx/html


networks:
  frontend:
  middleend:

